# Generated by Django 6.1.1 on 2026-09-22 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_images/%Y/%m/', verbose_name='Изображение')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.post')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('website', models.URLField(blank=True, verbose_name='Сайт / портфолио')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('status', models.CharField(choices=[('newbie', 'Новичок'), ('member', 'Участник'), ('veteran', 'Ветеран'), ('moderator', 'Модератор'), ('banned', 'Заблокирован')], default='newbie', max_length=20)),
                ('is_banned', models.BooleanField(default=False, verbose_name='Забанен')),
                ('ban_reason', models.CharField(blank=True, max_length=255, verbose_name='Причина бана')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
