# Generated by Django 6.1.1 on 2026-09-23 00:00

import board.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_postimage_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=20000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to='post_images/%Y/%m/', validators=[board.validators.validate_image_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[board.validators.validate_image_size], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, verbose_name='О себе'),
        ),
    ]
