# Generated by Django 6.1.1 on 2026-09-23 00:39

import board.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_links_forward(apps, schema_editor):
    Profile = apps.get_model('board', 'Profile')
    ProfileLink = apps.get_model('board', 'ProfileLink')
    for profile in Profile.objects.all():
        order = 0
        if profile.website:
            ProfileLink.objects.create(profile=profile, label='Сайт', url=profile.website, order=order)
            order += 1
        if profile.github:
            ProfileLink.objects.create(profile=profile, label='GitHub', url=profile.github, order=order)


def copy_links_backward(apps, schema_editor):
    Profile = apps.get_model('board', 'Profile')
    ProfileLink = apps.get_model('board', 'ProfileLink')
    for profile in Profile.objects.all():
        link = profile.links.first()
        if link:
            profile.website = link.url
            profile.save(update_fields=['website'])


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_body_alter_postimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='board.profile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(copy_links_forward, copy_links_backward),
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
        migrations.CreateModel(
            name='PostAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_audio/%Y/%m/', validators=[board.validators.validate_audio_file], verbose_name='Аудио')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='board.post')),
            ],
        ),
    ]
